services:
  - name: web
    dockerfile: Dockerfile
    startCommand: python manage.py runserver 0.0.0.0:8000
    buildCommand: python manage.py collectstatic --noinput
    env:
      - key: DJANGO_SECRET_KEY
        value: <django-insecure-!y(l8=1v6t1cz$19*v0b3*f$e(k!k%vw$_5vh8=&#*bk%0pbq=>
    - key: DATABASE_URL
        value: sqlite:///db.sqlite3
